Name:           ros-kinetic-angles
Version:        1.9.10
Release:        0%{?dist}
Summary:        ROS angles package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/angles
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

BuildRequires:  ros-kinetic-catkin >= 0.5.68

%description
This package provides a set of simple math utilities to work with angles. The
utilities cover simple things like normalizing an angle and conversion between
degrees and radians. But even if you're trying to calculate things like the
shortest angular distance between two joinst space positions of your robot, but
the joint motion is constrained by joint limits, this package is what you need.
The code in this packge is stable and well tested. There are no plans for major
changes in the near future.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Mar 18 2016 Ioan Sucan <isucan@willowgarage.com> - 1.9.10-0
- Autogenerated by Bloom

